---
name: "Linters"

# yamllint disable-line rule:truthy
on: ["pull_request"]

jobs:
  validate-commits:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out code into the Go module directory"
        uses: "actions/checkout@v1"
      - name: "Commitsar check"
        uses: "docker://aevea/commitsar:0.16.0"
  yamllint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - name: "yamllint"
        uses: "reviewdog/action-yamllint@v1"
        with:
          github_token: "${{ secrets.github_token }}"
          reporter: "github-pr-review"
          filter_mode: "nofilter"
