---
name: "Linters"

on: ["pull_request"]  # yamllint disable-line rule:truthy

jobs:
  validate-commits:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out code into the Go module directory"
        uses: "actions/checkout@v1"
      - name: "Commitsar check"
        uses: "aevea/commitsar@v0.16.0"
  yamllint:
    name: "runner / yamllint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - name: "yamllint"
        uses: "reviewdog/action-yamllint@v1"
        with:
          github_token: "${{ secrets.github_token }}"
          filter_mode: "nofilter"
          reporter: "github-pr-review"
